<?php
for($t=0;$t<360;$t++)
{
 $y=2*cos($t)-cos(2*$t);
 $x=2*sin($t)-sin(2*$t);
 $x+=3;
 $y+=3;
 $x*=70;
 $y*=70;
 $x=round($x);
 $y=round($y);
 $str[]=$x;
 $y=$y+2*(180-$y);
 $x=$y;
 $str[]=$x;
}
 $im=imagecreate(400,400);
 $black=imagecolorallocate($im,0,0,0);
 $red=imagecolorallocate($im,255,0,0);
 imagepolygon($im,$str,360,$red);
 imagestring($im,5,190,190,"love",$red);
 header('Content-type:image/gif');
 imagegif($im);
 imagedestroy($im);
?>